name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: rustup install stable

      - uses: actions/cache@v3
        with:
          # Refer from: https://github.com/actions/cache/blob/8bec1e4cc329270e6364af0aee38d62e50012e62/examples.md#rust---cargo
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
